@startuml

title __DB's Class Diagram__\n

  package org.jamienicol.episodes {
    package org.jamienicol.episodes.db {
      class BackUpRestoreHelper {
          {static} - TAG : String
          {static} + backUp()
          {static} + restore()
          {static} + getBackupDir()
      }
    }
  }
  

  package org.jamienicol.episodes {
    package org.jamienicol.episodes.db {
      class BackUpTask {
          - context : Context
          - destFilePath : String
          + BackUpTask()
          # doInBackground()
          # onPostExecute()
          {static} - getBackupFilename()
      }
    }
  }
  

  package org.jamienicol.episodes {
    package org.jamienicol.episodes.db {
      class RestoreTask {
          - context : Context
          + RestoreTask()
          # doInBackground()
          # onPostExecute()
      }
    }
  }
  

  package org.jamienicol.episodes {
    package org.jamienicol.episodes.db {
      class DatabaseOpenHelper {
          {static} - name : String
          {static} - version : int
          {static} - TAG : String
          ~ DatabaseOpenHelper()
          + onCreate()
          + onUpgrade()
          + onOpen()
          {static} + getDbName()
      }
    }
  }
  

  package org.jamienicol.episodes {
    package org.jamienicol.episodes.db {
      class EpisodesTable {
          {static} - TAG : String
          {static} + TABLE_NAME : String
          {static} + COLUMN_ID : String
          {static} + COLUMN_TVDB_ID : String
          {static} + COLUMN_SHOW_ID : String
          {static} + COLUMN_NAME : String
          {static} + COLUMN_OVERVIEW : String
          {static} + COLUMN_EPISODE_NUMBER : String
          {static} + COLUMN_SEASON_NUMBER : String
          {static} + COLUMN_FIRST_AIRED : String
          {static} + COLUMN_WATCHED : String
          {static} + onCreate()
          {static} + onUpgrade()
      }
    }
  }
  

  package org.jamienicol.episodes {
    package org.jamienicol.episodes.db {
      class ShowsProvider {
          {static} - TAG : String
          {static} - URI_AUTHORITY : String
          {static} - CONTENT_URI_BASE : Uri
          {static} + CONTENT_URI_SHOWS : Uri
          {static} + CONTENT_URI_EPISODES : Uri
          {static} + CONTENT_TYPE_SHOW_DIR : String
          {static} + CONTENT_TYPE_SHOW_ITEM : String
          {static} + CONTENT_TYPE_EPISODE_DIR : String
          {static} + CONTENT_TYPE_EPISODE_ITEM : String
          {static} - URI_TYPE_SHOWS : int
          {static} - URI_TYPE_SHOWS_ID : int
          {static} - URI_TYPE_EPISODES : int
          {static} - URI_TYPE_EPISODES_ID : int
          {static} - uriMatcher : UriMatcher
          + query()
          + insert()
          + delete()
          + update()
          + getType()
          + onCreate()
          {static} + reloadDatabase()
      }
    }
  }
  

  package org.jamienicol.episodes {
    package org.jamienicol.episodes.db {
      class ShowsTable {
          {static} - TAG : String
          {static} + TABLE_NAME : String
          {static} + COLUMN_ID : String
          {static} + COLUMN_TVDB_ID : String
          {static} + COLUMN_LANGUAGE : String
          {static} + COLUMN_NAME : String
          {static} + COLUMN_OVERVIEW : String
          {static} + COLUMN_FIRST_AIRED : String
          {static} + COLUMN_STARRED : String
          {static} + COLUMN_BANNER_PATH : String
          {static} + COLUMN_FANART_PATH : String
          {static} + COLUMN_POSTER_PATH : String
          {static} + COLUMN_NOTES : String
          {static} + COLUMN_TYPE_ID : String
          {static} + COLUMN_TYPE_TVDB_ID : String
          {static} + COLUMN_TYPE_LANGUAGE : String
          {static} + COLUMN_TYPE_NAME : String
          {static} + COLUMN_TYPE_OVERVIEW : String
          {static} + COLUMN_TYPE_FIRST_AIRED : String
          {static} + COLUMN_TYPE_STARRED : String
          {static} + COLUMN_TYPE_BANNER_PATH : String
          {static} + COLUMN_TYPE_FANART_PATH : String
          {static} + COLUMN_TYPE_POSTER_PATH : String
          {static} + COLUMN_TYPE_NOTES : String
          {static} + onCreate()
          {static} + onUpgrade()
      }
    }
  }
  

  BackUpRestoreHelper +-down- BackUpTask
  BackUpRestoreHelper +-down- RestoreTask
  BackUpTask -up-|> AsyncTask
  RestoreTask -up-|> AsyncTask
  DatabaseOpenHelper -up-|> SQLiteOpenHelper
  ShowsProvider -up-|> ContentProvider
  ShowsProvider o-- DatabaseOpenHelper : databaseOpenHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
